<?php
/**
 * Created by PhpStorm.
 * User: UlSi
 * Date: 06.09.2016
 * Time: 13:35
 */
class questions_model extends MY_Model {

    /*My_Model variables definitions */
    protected  $_table = "t_question";
    protected $primary_key = "id";
    protected $belong_to = [''];
    protected $has_many = [''];

    protected $after_get = ['get','get_all','insert','update','delete'];

    /*Constructeur*/
    public function __construct()
    {
        parent::__construct();
    }

    public function get($primary_value)
    {
        return parent::get($primary_value); // TODO: Change the autogenerated stub
    }

    public function get_all()
    {
        return parent::get_all(); // TODO: Change the autogenerated stub
    }

    public function insert($data, $skip_validation = FALSE)
    {
        return parent::insert($data, $skip_validation); // TODO: Change the autogenerated stub
    }

    public function update($primary_value, $data, $skip_validation = FALSE)
    {
        return parent::update($primary_value, $data, $skip_validation); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }


}